<a href="https://colab.research.google.com/github/VishnuGupta5883/appliedai/blob/master/Python_Mandatory_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [18 24 30 36 42]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [0]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
# here A and B are list of lists
def result_mat(A,B):
  result =[]
  for i in range(len(A)):
    rowlist =[]
    for j in range(len(B[0])):
      rowlist.append(0)
    result.append(rowlist)
  return result

def matrix_mul(A, B):
    # write your code
    if len(A[0])!=len(B):
      print("Multiplication not possible")
    else:
      res = result_mat(A,B)
      for i in range(len(A)):
        for j in range(len(B[0])):
           
          for k in range(len(B)):
            res[i][j] += A[i][k] * B[k][j]
      print(res)

A   = [[1, 2],[3, 4]]
B   = [[1, 4],[5, 6],[7, 8],[9, 6]]    
matrix_mul(A, B)

Multiplication not possible


<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [95]:
from random import uniform
import random
from itertools import accumulate
from bisect import bisect
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

A = [0, 5, 27, 6, 13, 28, 100, 45, 10, 79]
https://stackoverflow.com/questions/57162832/find-propotional-sampling-using-python

# you can free to change all these codes/structure

def pick_a_number_from_list(A, n=100):
    # calculate cumulative sum from A:
    cum_sum = [*accumulate(A)]
    # cum_sum = [0, 5, 32, 38, 51, 79, 179, 224, 234, 313]

    out = []
    for _ in range(n):
        i = random.random()                     # i = [0.0, 1.0)
        idx = bisect(cum_sum, i*cum_sum[-1])    # get index to list A
        out.append(A[idx])
    return out
number = pick_a_number_from_list(A)
print(number)



[13, 79, 100, 100, 28, 45, 79, 100, 6, 79, 28, 45, 13, 100, 79, 79, 79, 79, 45, 100, 79, 28, 27, 100, 100, 100, 45, 100, 79, 79, 6, 79, 100, 100, 100, 100, 100, 6, 100, 79, 45, 28, 100, 79, 100, 28, 28, 45, 45, 79, 27, 27, 100, 27, 5, 100, 100, 79, 100, 79, 79, 79, 6, 45, 28, 100, 13, 79, 100, 28, 79, 100, 79, 5, 27, 45, 6, 45, 79, 79, 79, 100, 79, 5, 79, 79, 13, 100, 6, 79, 28, 13, 13, 5, 79, 79, 13, 45, 100, 45]


<h3> Q3: Replace the digits in the string with #</h3>

Consider a string that will have digits in that, we need to remove all the characters which are not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [0]:
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
# String: it will be the input to your program
String = 'a2b3c4'
def replace_digits(String):
    result = re.sub("[a-z $%#]", '', String)
    result = re.sub("[0-9]", '#',result)   
    return result # modified string which is after replacing the # with digits

replace_digits(String)

'###'

<h3> Q4: Students marks dashboard</h3>

Consider the marks list of class students given in two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on. <br><br>

Your task is to print the name of students

<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks.</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

a. 
student8  98
student10 80
student2  78
student5  48
student7  47

b.
student3 12
student4 14
student9 35
student6 43
student1 45

c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [87]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
def display_dash_board(students, marks):
  dict={}
  mark2 = marks;
  mark2.sort() 
  #print(mark2)

  p25 = (25 *(len(mark2)+ 1))/100
  p75 = (75 *(len(mark2)+ 1))/100
  q25 = mark2[int(p25)-1] # to calculate 25th percentile
  q75 = mark2[int(p75)-1] # to calculate 75th percentile
  #print(q25, q75)

  for i in students:
    for j in marks:
      dict[i]=j
      marks.remove(j)
      break
  #print(dict)

  top_5_students = sorted(dict.items(), key=lambda x: x[1], reverse=True)
  top_5_students = top_5_students[:5]
      # write code for computing top least 5 students
  least_5_students = sorted(dict.items(), key=lambda x: x[1], reverse=False)
  least_5_students =least_5_students[:5]
  
  a =  {key:value for key,value in dict.items() if value > q25 and value < q75 }
  students_within_25_and_75 = sorted(a.items(), key=lambda x: x[1], reverse=False)

  #print(top_5_students,least_5_students,students_within_25_and_75)
    
  return top_5_students, least_5_students, students_within_25_and_75

students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

top_5_students, least_5_students, students_within_25_and_75 = display_dash_board(students, marks)
print("top_5_students:",top_5_students)
print("least_5_students:",least_5_students)
print("students_within_25_and_75:",students_within_25_and_75)


top_5_students: [('student10', 98), ('student9', 80), ('student8', 78), ('student7', 48), ('student6', 47)]
least_5_students: [('student1', 12), ('student2', 14), ('student3', 35), ('student4', 43), ('student5', 45)]
students_within_25_and_75: [('student3', 35), ('student4', 43), ('student5', 45), ('student6', 47), ('student7', 48)]


<h3> Q5: Find the closest points</h3>

Consider you are given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P

<br>Cosine distance between two points (x,y) and (p,q) is defined as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [58]:
import math
import numpy as np
from numpy.linalg import norm

# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can free to change all these codes/structure


# here S is list of tuples and P is a tuple ot len=2
def closest_points_to_p(S, P):
  dict ={}; closest_points_to_p=[];
  for i in range(len(S)):
    cos_d = math.acos(np.dot(S[i],P)/(norm(S[i])*norm(P)))
    #print(cos_d,S[i])
    dict[S[i]] = cos_d
  #print(dict)
  dict = sorted(dict.items(), key=lambda x: x[1], reverse=False)
  dict =dict[:5]
  print(dict)
  for i in dict:
    closest_points_to_p.append(i[0])
  return closest_points_to_p  # its list of tuples

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)
points = closest_points_to_p(S, P)
print(points) #print the returned values

[((6, -7), 0.06512516333438509), ((1, -1), 0.14189705460416438), ((6, 0), 0.9272952180016123), ((-5, -8), 1.2021004241368467), ((-1, -1), 1.4288992721907328)]
[(6, -7), (1, -1), (6, 0), (-5, -8), (-1, -1)]


<h3> Q6: Find which line separates oranges and apples</h3>

Consider you are given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string format, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: You need to do string parsing here and get the coefficients of x,y and intercept.
</pre>
Your task here is to print "YES"/"NO" for each line given. You should print YES, if all the red points are one side of the line and blue points are on other side of the line, otherwise you should print NO.
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [0]:
import math
from prettytable import PrettyTable
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def i_am_the_one(Red,Blue,lines):
  x = PrettyTable()
  x.field_names = ["Line","Red Points one side","Blue Points on other side","FINAL Result"]

  
  line1 =[]
  for i in lines:
    z = re.findall(r'[\d\.\-\+]+', i)
    line1.append(z)
  #print(line1)

  dicR ={}
  dicB ={}
  dicRF ={}
  dicBF ={}
  tuple1 =()
  #for i in range(len(Red)):
  for k in line1:
    for j in Red:
      a= (int(k[0]) * j[0]) + (int(k[1]) * j[1]) + (float(k[2]));
      dicR[j] =a;       
    #print("Red Points",dicR)
    for l in Blue:
      b= (int(k[0]) * l[0]) + (int(k[1]) * l[1]) + (float(k[2]));
      dicB[l] =b;
    #print("Blue points",dicB)
    for key,value in dicR.items():
      if value > 0.0:
        dicRF[str(k)] ='YES'
      else:
        dicRF[str(k)] ='NO'
    #print("Red points",dicRF)
    for key,value in dicB.items():
      if value < 0.0:
        dicBF[str(k)] ='YES'
      else:
        dicBF[str(k)] ='NO'
  #print("Blue points",dicBF)
    if (dicRF[str(k)] ==dicBF[str(k)]) and dicRF[str(k)] =='YES':
      x.add_row([str(k),dicRF[str(k)], dicBF[str(k)],"YES"])
    else: 
      x.add_row([str(k),dicRF[str(k)], dicBF[str(k)],"NO"])
#print(x)
  return x

Red= [(1,1),(2,1),(4,2),(2,4),(-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

#for i in Lines:
yes_or_no = i_am_the_one(Red, Blue, Lines)
print(yes_or_no) # the returned value

+---------------------+---------------------+---------------------------+--------------+
|         Line        | Red Points one side | Blue Points on other side | FINAL Result |
+---------------------+---------------------+---------------------------+--------------+
|  ['1', '+1', '+0']  |         YES         |            YES            |     YES      |
|  ['1', '-1', '+0']  |          NO         |             NO            |      NO      |
|  ['1', '+0', '-3']  |          NO         |            YES            |      NO      |
| ['0', '+1', '-0.5'] |         YES         |            YES            |     YES      |
+---------------------+---------------------+---------------------------+--------------+


<h3> Q7: Filling the missing values in the specified format</h3>

You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 

<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [111]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
https://stackoverflow.com/questions/57179618/filling-the-missing-values-in-the-specified-format-python

def fun(x, a, b):
    if a == -1:
        v = float(x[b])/(b+1)
        for i in range(a+1,b+1):
            x[i] = v
    elif b == -1:
        v = float(x[a])/(len(x)-a)
        for i in range(a, len(x)):
            x[i] = v
    else:
        v = (float(x[a])+float(x[b]))/(b-a+1)
        for i in range(a,b+1):
            x[i] = v
    return x

def replace(text):
    # Create array from the string
    x = text.replace(" ","").split(",")
    # Get all the pairs of indices having number
    y = [i for i, v in enumerate(x) if v != '_']
    # Starting with _ ?
    if y[0] != 0:
        y = [-1] + y
    # Ending with _ ?
    if y[-1] != len(x)-1:
        y = y + [-1]    
    # run over all the pairs
    for (a, b) in zip(y[:-1], y[1:]): 
        fun(x,a,b)          
    return x

# Test cases
tests = [
    "_,_,_,24",
    "40,_,_,_,60",
    "80,_,_,_,_",
     "_,_,30,_,_,_,50,_,_"]

for i in tests:
    print (replace(i))


[6.0, 6.0, 6.0, 6.0]
[20.0, 20.0, 20.0, 20.0, 20.0]
[16.0, 16.0, 16.0, 16.0, 16.0]
[10.0, 10.0, 12.0, 12.0, 12.0, 12.0, 4.0, 4.0, 4.0]


<h3> Q8: Find the probabilities</h3>

You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. The first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. The second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>



In [0]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings



# you can free to change all these codes/structure
def compute_conditional_probabilites(A):

  F= []
  S= []
  for i in A:
    if i[0] in F:
      continue
    else:
      F.append(i[0])
    if i[1] in S:
      continue
    else:
      S.append(i[1])

  counts1=0
  countf1s1 =0
  countf2s1 =0
  countf3s1 =0
  countf4s1 =0
  countf5s1 =0
  counts2=0
  countf1s2 =0
  countf2s2 =0
  countf3s2 =0
  countf4s2 =0
  countf5s2 =0
  counts3=0
  countf1s3 =0
  countf2s3 =0
  countf3s3 =0
  countf4s3 =0
  countf5s3 =0

  for i in A:
    if i[1]==S[0]:
      counts1 = counts1 + 1
      if i[0]==F[0]:
        countf1s1 = countf1s1 + 1
      elif i[0]==F[1]:
        countf2s1 = countf2s1 + 1
      elif i[0]==F[2]:
        countf3s1 = countf3s1 + 1
      elif i[0]==F[3]:
        countf4s1 = countf4s1 + 1
      else:
        countf5s1 = countf5s1 + 1
    elif i[1]==S[1]:
      counts2 = counts2 + 1
      if i[0]==F[0]:
        countf1s2 = countf1s2 + 1
      elif i[0]==F[1]:
        countf2s2 = countf2s2 + 1
      elif i[0]==F[2]:
        countf3s2 = countf3s2 + 1
      elif i[0]==F[3]:
        countf4s2 = countf4s2 + 1
      else:
        countf5s2 = countf5s2 + 1
    elif i[1]==S[2]:
      counts3 = counts3 + 1
      if i[0]==F[0]:
        countf1s3 = countf1s3 + 1
      elif i[0]==F[1]:
        countf2s3 = countf2s3 + 1
      elif i[0]==F[2]:
        countf3s3 = countf3s3 + 1
      elif i[0]==F[3]:
        countf4s3 = countf4s3 + 1
      else:
        countf5s3 = countf5s3 + 1


  print("P(F=F1|S==S1)=",str(countf1s1) + "/" + str(counts1),",P(F=F1|S==S2)=",str(countf1s2) + "/" + str(counts2),",P(F=F1|S==S3)=",str(countf1s3) + "/" + str(counts3))
  print("P(F=F2|S==S1)=",str(countf2s1) + "/" + str(counts1),",P(F=F2|S==S2)=",str(countf2s2) + "/" + str(counts2),",P(F=F2|S==S3)=",str(countf2s3) + "/" + str(counts3))
  print("P(F=F3|S==S1)=",str(countf3s1) + "/" + str(counts1),",P(F=F3|S==S2)=",str(countf3s2) + "/" + str(counts2),",P(F=F3|S==S3)=",str(countf3s3) + "/" + str(counts3))
  print("P(F=F4|S==S1)=",str(countf4s1) + "/" + str(counts1),",P(F=F4|S==S2)=",str(countf4s2) + "/" + str(counts2),",P(F=F4|S==S3)=",str(countf4s3) + "/" + str(counts3))
  print("P(F=F5|S==S1)=",str(countf5s1) + "/" + str(counts1),",P(F=F5|S==S2)=",str(countf5s2) + "/" + str(counts2),",P(F=F5|S==S3)=",str(countf5s3) + "/" + str(counts3))

#A = [[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]
A = [[1,7],[2,8],[3,9],[1,8],[2,9],[3,8],[2,7],[4,7],[4,9],[5,7]]
compute_conditional_probabilites(A)

P(F=F1|S==S1)= 1/4 ,P(F=F1|S==S2)= 1/3 ,P(F=F1|S==S3)= 0/3
P(F=F2|S==S1)= 1/4 ,P(F=F2|S==S2)= 1/3 ,P(F=F2|S==S3)= 1/3
P(F=F3|S==S1)= 0/4 ,P(F=F3|S==S2)= 1/3 ,P(F=F3|S==S3)= 1/3
P(F=F4|S==S1)= 1/4 ,P(F=F4|S==S2)= 0/3 ,P(F=F4|S==S3)= 1/3
P(F=F5|S==S1)= 1/4 ,P(F=F5|S==S2)= 0/3 ,P(F=F5|S==S3)= 0/3


<h3> Q9: Operations on sentences </h3>

You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 unique values"
S2= "the second column S will contain only 3 unique values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [0]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features(S1, S2):
  elem1 = [x for x in S1.split()]
  elem2 = [x for x in S2.split()]
  lst  =[]
  lst2 =[]
  lst3 =[]
  for item in elem1:
      if item in elem2:
        lst3.append(item)
  #print(len(lst3))
  a=len(lst3)

  for item in elem1:
      if item not in elem2:
        lst.append(item)
  #print(lst)
  b=lst

  for item in elem2:
      if item not in elem1:
        lst2.append(item)
  #print(lst2)
  c=lst2

  
  return a, b, c

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
a,b,c = string_features(S1, S2)
print(a,b,c)

<h3> Q10: Error Function</h3>

You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.44982
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [0]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
import math

# you can free to change all these codes/structure
def compute_log_loss(A):
  n =len(A)

  logloss =0.0
  for i in A:
    y = i[0]
    y_score = i[1]
    #logloss = logloss + (Ylog10(Yscore)+(1−Y)log10(1−Yscore))
    logloss  = logloss + ((y* (math.log10(y_score))) + ((1-y)*(math.log10(1-y_score))))
  final_logloss = -(logloss/float(n))
  return final_logloss

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print(loss)

0.42430993457031635
