<a href="https://colab.research.google.com/github/VishnuGupta5883/appliedai/blob/master/Python_Mandatory_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [18 24 30 36 42]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [0]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
# here A and B are list of lists


def result_mat(A,B):
  result =[]
  for i in range(len(A)):
    rowlist =[]
    for j in range(len(B[0])):
      rowlist.append(0)
    result.append(rowlist)
  return result

def matrix_mul(A, B):
    # write your code
    if len(A[0])!=len(B):
      print("Multiplication not possible")
    else:
      res = result_mat(A,B)
      for i in range(len(A)):
        for j in range(len(B[0])):
           
          for k in range(len(B)):
            res[i][j] += A[i][k] * B[k][j]
      print(res)
    
matrix_mul(A, B)

Multiplication not possible


<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [0]:
from random import uniform
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

A = [0, 5, 27, 6, 13, 28, 100, 45, 10, 79]

# you can free to change all these codes/structure
def pick_a_number_from_list(A):
    # your code here for picking an element from with the probability propotional to its magnitude
    #for i in A:
    #  print(i)
    max_n = max(A)
    min_n = min(A)
    x = uniform(min_n, max_n)  
    return x

def sampling_based_on_magnitued():
    for i in range(1,100):
        number = pick_a_number_from_list(A)
        print(number)

sampling_based_on_magnitued()

16.952460724848063
62.89323627713157
73.04613243084258
82.04338154779954
62.04085259999677
66.63588524222301
13.554824293061785
97.25018648917202
98.14639222886532
82.50471658673527
86.00757094779843
55.602115560624256
87.8442015808401
63.64247887258912
84.04311026535129
95.56503580280781
39.75092505205009
89.60963228552869
77.70202385391049
87.44443799319566
26.85040441457458
41.73210960741851
98.2461272579372
45.578513223697406
71.65377108174054
66.30029286484312
0.9410377009968163
30.078071277048647
26.420935122057777
50.071576576841125
26.380377231736485
42.11587629279162
57.97222599386648
16.906264178956686
52.34165649059894
57.218096547651356
76.49215701565092
4.693852501037132
55.593532328794204
83.8982517716374
96.61418841404104
38.05059181578761
86.24084189050659
53.57149858481725
26.535261568495095
13.361519236863295
56.642167984640935
97.3490217036097
26.118936348789703
3.81605922113607
70.19605698668923
29.93043938758324
14.059264182219511
95.75890016723974
99.1593574469521

<h3> Q3: Replace the digits in the string with #</h3>

Consider a string that will have digits in that, we need to remove all the characters which are not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [0]:
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
# String: it will be the input to your program
String = 'a2b3c4'
def replace_digits(String):
    result = re.sub("[a-z $%#]", '', String)
    result = re.sub("[0-9]", '#',result)   
    return result # modified string which is after replacing the # with digits

replace_digits(String)

'###'

<h3> Q4: Students marks dashboard</h3>

Consider the marks list of class students given in two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on. <br><br>

Your task is to print the name of students

<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks.</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

a. 
student8  98
student10 80
student2  78
student5  48
student7  47

b.
student3 12
student4 14
student9 35
student6 43
student1 45

c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [0]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
# you can free to change all these codes/structure
def display_dash_board(students, marks):
  dict={}
  for i in students:
    for j in Marks:
      dict[i]=j
      Marks.remove(j)
      break
    
    #https://stackoverflow.com/questions/613183/how-do-i-sort-a-dictionary-by-value
    # write code for computing top top 5 students
  top_5_students = sorted(dict.items(), key=lambda x: x[1], reverse=True)
  top_5_students = top_5_students[:5]
    # write code for computing top least 5 students
  least_5_students = sorted(dict.items(), key=lambda x: x[1], reverse=False)
  least_5_students =least_5_students[:5]
    # write code for computing students having >25th percentile <75th percentile, in the increasing order of marks
  a = {key:value for key,value in dict.items() if value > 25 and value < 75 }
  students_within_25_and_75 = sorted(a.items(), key=lambda x: x[1], reverse=False)
  print(top_5_students, least_5_students, students_within_25_and_75)
    
  return top_5_students, least_5_students, students_within_25_and_75

top_5_students, least_5_students, students_within_25_and_75 = display_dash_board(students, marks)
#print(top_5_students, least_5_students, students_within_25_and_75)
print(students_within_25_and_75)

[] [] []
[]


In [0]:
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

dict={}

for i in Students:
  for j in Marks:
    dict[i]=j
    Marks.remove(j)
    break
#print(dict)

top_5_students = sorted(dict.items(), key=lambda x: x[1], reverse=True)
top_5_students = top_5_students[:5]
    # write code for computing top least 5 students
least_5_students = sorted(dict.items(), key=lambda x: x[1], reverse=False)
least_5_students =least_5_students[:5]
a =  {key:value for key,value in dict.items() if value > 25 and value < 75 }
students_within_25_and_75 = sorted(a.items(), key=lambda x: x[1], reverse=False)

print(top_5_students,least_5_students,students_within_25_and_75)




[('student8', 98), ('student10', 80), ('student2', 78), ('student5', 48), ('student7', 47)] [('student3', 12), ('student4', 14), ('student9', 35), ('student6', 43), ('student1', 45)] [('student9', 35), ('student6', 43), ('student1', 45), ('student7', 47), ('student5', 48)]


<h3> Q5: Find the closest points</h3>

Consider you are given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P

<br>Cosine distance between two points (x,y) and (p,q) is defined as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [111]:
import math
import numpy as np
from numpy.linalg import norm

# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can free to change all these codes/structure


# here S is list of tuples and P is a tuple ot len=2
def closest_points_to_p(S, P):
  dict ={}; closest_points_to_p=[];
  for i in range(len(S)):
    cos_d = math.cos(np.dot(S[i],P)/(norm(S[i])*norm(P)))
    #print(cos_d,S[i])
    dict[S[i]] = cos_d
  #print(dict)
  dict = sorted(dict.items(), key=lambda x: x[1], reverse=False)
  dict =dict[:5]
  print(dict)
  for i in dict:
    closest_points_to_p.append(i[0])
  return closest_points_to_p  # its list of tuples

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)
points = closest_points_to_p(S, P)
print(points) #print the returned values

[((6, -7), 0.5420849198071851), ((-1, 1), 0.5487320844930946), ((1, -1), 0.5487320844930946), ((0, 6), 0.6967067093471654), ((6, 0), 0.8253356149096783)]
[(6, -7), (-1, 1), (1, -1), (0, 6), (6, 0)]


<h3> Q6: Find which line separates oranges and apples</h3>

Consider you are given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string format, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: You need to do string parsing here and get the coefficients of x,y and intercept.
</pre>
Your task here is to print "YES"/"NO" for each line given. You should print YES, if all the red points are one side of the line and blue points are on other side of the line, otherwise you should print NO.
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [97]:
import math
from prettytable import PrettyTable
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def i_am_the_one(Red,Blue,lines):
  x = PrettyTable()
  x.field_names = ["Line","Red Points","Blue Points","FINAL Result"]

  
  line1 =[]
  for i in lines:
    z = re.findall(r'[\d\.\-\+]+', i)
    line1.append(z)
  #print(line1)

  dicR ={}
  dicB ={}
  dicRF ={}
  dicBF ={}
  tuple1 =()
  #for i in range(len(Red)):
  for k in line1:
    for j in Red:
      a= (int(k[0]) * j[0]) + (int(k[1]) * j[1]) + (float(k[2]));
      dicR[j] =a;       
    #print("Red Points",dicR)
    for l in Blue:
      b= (int(k[0]) * l[0]) + (int(k[1]) * l[1]) + (float(k[2]));
      dicB[l] =b;
    #print("Blue points",dicB)
    for key,value in dicR.items():
      if value > 0.0:
        dicRF[str(k)] ='YES'
      else:
        dicRF[str(k)] ='NO'
    #print("Red points",dicRF)
    for key,value in dicB.items():
      if value < 0.0:
        dicBF[str(k)] ='YES'
      else:
        dicBF[str(k)] ='NO'
  #print("Blue points",dicBF)
    if (dicRF[str(k)] ==dicBF[str(k)]) and dicRF[str(k)] =='YES':
      x.add_row([str(k),dicRF[str(k)], dicBF[str(k)],"YES"])
    else: 
      x.add_row([str(k),dicRF[str(k)], dicBF[str(k)],"NO"])
#print(x)
  return x

Red= [(1,1),(2,1),(4,2),(2,4),(-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

#for i in Lines:
yes_or_no = i_am_the_one(Red, Blue, Lines)
print(yes_or_no) # the returned value

+---------------------+------------+-------------+--------------+
|         Line        | Red Points | Blue Points | FINAL Result |
+---------------------+------------+-------------+--------------+
|  ['1', '+1', '+0']  |    YES     |     YES     |     YES      |
|  ['1', '-1', '+0']  |     NO     |      NO     |      NO      |
|  ['1', '+0', '-3']  |     NO     |     YES     |      NO      |
| ['0', '+1', '-0.5'] |    YES     |     YES     |     YES      |
+---------------------+------------+-------------+--------------+


<h3> Q7: Filling the missing values in the specified format</h3>

You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 

<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [0]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def curve_smoothing(string):
    # your code
    return #list of values

S=  "_,_,30,_,_,_,50,_,_"
smoothed_values= curve_smoothing(S)
print(# print above values)

In [146]:
S=  "_,_,30,_,_,_,50,_,_"

S_len = len(S)
Count =0
final = " "
for item in S.split(","):
  if item =='_':
    Count = Count + 1
    continue
  item1 = int(item)/(Count +1)
  print(item1)
  if item == '_':
    final = str(item1);
  else:
    final = item
  print(final)


10.0
30
8.333333333333334
50


In [148]:
S_len = len(S)
print(S_len)

19


<h3> Q8: Find the probabilities</h3>

You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. The first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. The second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>



In [0]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings



# you can free to change all these codes/structure
def compute_conditional_probabilites(A):
    # your code
    # print the output as per the instructions

A = [[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]
compute_conditional_probabilites(A)

<h3> Q9: Operations on sentences </h3>

You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 unique values"
S2= "the second column S will contain only 3 unique values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [128]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features(S1, S2):
  elem1 = [x for x in S1.split()]
  elem2 = [x for x in S2.split()]
  lst  =[]
  lst2 =[]
  lst3 =[]
  for item in elem1:
      if item in elem2:
        lst3.append(item)
  #print(len(lst3))
  a=len(lst3)

  for item in elem1:
      if item not in elem2:
        lst.append(item)
  #print(lst)
  b=lst

  for item in elem2:
      if item not in elem1:
        lst2.append(item)
  #print(lst2)
  c=lst2

  
  return a, b, c

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
a,b,c = string_features(S1, S2)
print(a,b,c)

7 ['first', 'F', '5'] ['second', 'S', '3']


<h3> Q10: Error Function</h3>

You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.44982
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [0]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def compute_log_loss(A):
    # your code
    
    return loss

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print(# the above loss)